### ISSUE TITLE
리뷰에 대한 질문사항이 있습니다.

### ISSUE THREAD

**Issue by JunilHwang** [connectfoundation/review_2020#1]
>`리뷰 작성시 유의 사항`
>- 예시 코드를 fork하여 리뷰를 작성합니다.
>- 작성한 리뷰는 각 저장소의 review 브랜치로 Pull Request 합니다.
>- PR 로그가 없는 경우 미지원으로 간주합니다.

에서 리뷰 과정이 정확히 어떻게 되는건가요?

제가 받아들이기에는 3가지 경우인데..

- fork한 저장소의 review 브랜치의 readme.md에다가 작성한 후에 PR을 해야한다
- fork한 저장소의 master에서 코드를 수정한 다음에 원본 저장소의 review에다가 PR을 한다.
- fork한 저장소의 master브랜치에서 review브랜치를 만든 다음에 코드를 수정 후 원본 저장소의 review에다가 PR을 한다

이 중에 어떤건지.. 혹은 아예 다른이야기인지.. 궁금합니다!

**Comment by connectfoundation** [comment]
@JunilHwang 
모호한 설명으로 불편을 드린 점 먼저 죄송하다는 말씀드립니다.
더 명확히 이해하실 수 있도록 서술을 개선했습니다.

* 리뷰할 코드의 저장소를 fork합니다.
* 리뷰를 작성하기 위해 저장소의 비어있는 review 브랜치로 Pull Request 합니다.
* 내가 오픈한 PR에 코드 리뷰 코멘트를 남깁니다.

일반적인 코드 리뷰 프로세스와는 약간의(?) 차이가 있지만
개별 지원자의 리뷰 로그를 구분하기 위한 방식임을 양해 부탁드려요 :)

감사합니다.

**Comment by JunilHwang** [comment]
@connectfoundation 
답변 감사합니다! 음 제가 제대로 이해한건지 확인차 다시 여쭤봅니다!

포크 후 바로 review 브랜치로 PR을 날린다음에 PR 코멘트로 원본 소스에 대한 리뷰를 남기면 되는걸까요?

**Comment by eomttt** [comment]
저도 그부분이 궁금했는데 
포크 한 후 review 브렌치로 PR을 날리라는 거가 맞는건지요?

**Comment by connectfoundation** [comment]
@JunilHwang @eomttt 네, 맞습니다 :) 바르게 이해하셨습니다
(노티를 놓쳐서 답신이 늦어진 부분 죄송합니다)
